/**
 * server - App Factory
 * Generated by Arc CLI
 *
 * Creates and configures the Fastify app instance.
 * Can be imported by:
 * - index.ts (HTTP server via app.listen, or edge handler via toFetchHandler)
 * - worker.ts (background workers)
 * - tests (integration tests via app.inject)
 */

import { createBetterAuthAdapter } from '@classytic/arc/auth';
import { createApp } from '@classytic/arc/factory';
import type { FastifyInstance } from 'fastify';
import mongoose from 'mongoose';
import config from '#config/index.js';
// App-specific plugins
import { registerPlugins } from '#plugins/index.js';
// Resource registry — createApp({ resources }) mounts each one under the
// resourcePrefix below; no manual registration loop needed.
import { resources } from '#resources/index.js';
import { getAuth } from './auth.js';
import { registerMcpEndpoint } from './mcp/index.js';
import { setAt1FilingGateway } from './filing/at1-gateway.js';
import { at1SoapClientFromEnv } from './filing/at1-soap-client.js';

/**
 * Create a fully configured app instance
 *
 * @returns Configured Fastify instance ready to use
 */
export async function createAppInstance(): Promise<FastifyInstance> {
  // Create Arc app with resources and base configuration. `resourcePrefix`
  // mounts every resource under `/api`, matching the `apiPrefix` the
  // OpenAPI plugin advertises — keeps docs and routes in agreement.
  const app = await createApp({
    preset: config.env === 'production' ? 'production' : 'development',
    resources,
    resourcePrefix: '/api',
    auth: {
      type: 'betterAuth',
      betterAuth: createBetterAuthAdapter({ auth: getAuth(), orgContext: true }),
    },
    cors: {
      origin: config.cors.origins,
      methods: config.cors.methods,
      allowedHeaders: config.cors.allowedHeaders,
      credentials: config.cors.credentials,
    },
    // One proxy hop (the typical LB / reverse-proxy deploy). Widen to a CIDR
    // list or `true` only if you know every hop is yours; `false` if clients
    // connect directly. Arc's production preset defaults to `false` (fail-closed).
    trustProxy: 1,
    arcPlugins: {
      metrics: config.env === 'production', // Prometheus /_metrics endpoint
      // Readiness probe (/_health/ready) reports DOWN until Mongo connects —
      // K8s / load balancers hold traffic until the app can actually serve.
      health: {
        checks: [{ name: 'mongodb', check: () => mongoose.connection.readyState === 1 }],
      },
    },
    // Drain the DB connection on shutdown. Arc's gracefulShutdown (on by
    // default) calls app.close() on SIGTERM/SIGINT, which runs this hook —
    // no manual signal handlers needed.
    onClose: async () => {
      await mongoose.disconnect();
    },
  });

  // Register app-specific plugins (explicit dependency injection)
  await registerPlugins(app, { config });

  // MCP endpoint (/api/mcp) — auto-generates one tool per CRUD verb + action on
  // every arc resource, so an AI agent can operate the tax system through the
  // same governed handlers the UI uses. Auth is per-org API keys (see auth.ts).
  await registerMcpEndpoint(app, { resources, auth: getAuth() });

  // Alberta Net File transmission. Installed ONLY when an endpoint is
  // configured — absent it, the gateway keeps its 503 stub, so a dev or test
  // environment can never write a filing record for a return that was never
  // sent. Alberta is the one jurisdiction this is possible for: TRA publishes
  // the WSDL and the response codes, while CRA and Revenu Québec release their
  // schemas only through their certification programmes.
  const traClient = at1SoapClientFromEnv();
  if (traClient) {
    setAt1FilingGateway(traClient);
    app.log.info('AT1 Net File gateway installed (TRA_NETFILE_ENDPOINT configured)');
  } else {
    app.log.info('AT1 Net File gateway NOT configured — transmission will refuse with 503');
  }

  return app;
}

export default createAppInstance;
