/**
 * Better Auth Configuration
 * Generated by Arc CLI
 *
 * Better Auth owns auth flows + writes its own tables. Arc reads them as
 * resources via `@classytic/mongokit/better-auth`'s overlay (full pagination,
 * queryparser, OpenAPI, audit) without re-implementing CRUD.
 *
 * BA-managed tables: user, session, account, verification, organization, member, invitation, team, teamMember
 *
 * @see https://www.better-auth.com/docs
 */

import { apiKey } from '@better-auth/api-key';
import { mongodbAdapter } from '@better-auth/mongo-adapter';
import { registerBetterAuthStubs } from '@classytic/mongokit/better-auth';
import { betterAuth } from 'better-auth';
import { bearer, mcp } from 'better-auth/plugins';
import { organization } from 'better-auth/plugins/organization';
import mongoose from 'mongoose';
import config from '#config/index.js';

// Factory keeps the CONCRETE betterAuth({...}) instantiation as the source
// of truth for the instance type — annotating with the wide
// `Auth<BetterAuthOptions>` (aka `ReturnType<typeof betterAuth>`) does not
// typecheck because Better Auth's `Auth<T>` is generic over the exact
// options object.
function createAuth() {
  return betterAuth({
    secret: config.betterAuth.secret,
    baseURL: process.env.BETTER_AUTH_URL || `http://localhost:${config.server.port}`,
    basePath: '/api/auth',

    database: mongodbAdapter(mongoose.connection.getClient().db() as unknown as never),

    user: {
      additionalFields: {
        roles: {
          type: 'string[]',
          defaultValue: ['user'],
          required: false,
          input: false, // Cannot be set during signup
        },
      },
    },

    emailAndPassword: {
      enabled: true,
      minPasswordLength: 6,
    },

    // Google OAuth (enabled when env vars are set)
    ...(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET
      ? {
          socialProviders: {
            google: {
              clientId: process.env.GOOGLE_CLIENT_ID,
              clientSecret: process.env.GOOGLE_CLIENT_SECRET,
            },
          },
        }
      : {}),

    plugins: [
      // Session-token bearer auth (dashboard /api/* calls without a cookie).
      bearer(),
      // MCP plugin — arc detects it and auto-mounts OAuth 2.1 discovery so an
      // MCP client (Claude Desktop, Inspector, claude.ai connector) can log in
      // via the same page humans use. Tool calls resolve to { userId, org }.
      mcp({ loginPage: '/sign-in' }),
      // Long-lived, per-org API keys for MCP / CLI automation. Stored hashed;
      // each key is created with metadata.orgId so a call scopes to ONE org
      // without an extra header. Endpoints under /api/auth/api-key/*.
      apiKey({
        defaultPrefix: 'txf_',
        requireName: true,
        enableMetadata: true,
        keyExpiration: { defaultExpiresIn: null }, // never expire unless opted in
        startingCharactersConfig: { shouldStore: true, charactersLength: 12 },
      }),
      organization({
        allowUserToCreateOrganization: true,
        creatorRole: 'owner',
        teams: { enabled: true },
      }),
    ],
    session: {
      cookieCache: {
        enabled: true,
        maxAge: 5 * 60, // 5 minutes
      },
    },

    trustedOrigins: [config.frontend.url],

    rateLimit: {
      enabled: process.env.NODE_ENV === 'production',
    },
  });
}

// The `mcp()` / `apiKey()` plugins leak un-nameable option types into the
// inferred instance type (TS4058 at the export boundary), so — like fajr-be-arc
// — we hold the instance loosely. The concrete betterAuth({...}) call in
// createAuth() stays the source of truth for behaviour.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _auth: any = null;

/**
 * Get the Better Auth instance (lazy singleton)
 *
 * Must be called AFTER database connection is established.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getAuth(): any {
  if (process.env.NODE_ENV === 'production' && !process.env.BETTER_AUTH_SECRET) {
    throw new Error('BETTER_AUTH_SECRET is required in production (min 32 chars)');
  }

  // Narrow through a local — assigning the module-level `_auth` directly
  // would lose the non-null narrowing across the calls below.
  let auth = _auth;
  if (!auth) {
    auth = createAuth();
    _auth = auth;

    // Register stub Mongoose models for Better Auth's collections so
    // `.populate('user')` / `ref: 'organization'` resolve against BA-owned
    // documents app-wide. Idempotent, strict:false, plugin-aware.
    registerBetterAuthStubs(mongoose, { plugins: ['organization'] });
  }

  return auth;
}

export default getAuth;
